import Layout from "../components/Layout";
import Head from "next/head";
import Image from "next/image";
import img1 from "../img/about/1.gif";
import img2 from "../img/about/icn1.svg";
import img3 from "../img/about/icn2.svg";
import img4 from "../img/home/19.png";
import ScrollToTop from "react-scroll-to-top";
import AOS from "aos";
import "aos/dist/aos.css";
import { useEffect } from "react";

function About() {
  useEffect(() => {
    AOS.init();
    AOS.refresh();
  }, []);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@600&family=Nunito:wght@300&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>

      <Layout>
        <div className="flex justify-center mt-44 mb-24">
          <div className="lg:w-[1100px] md:w-[700px] sm:w-[500px] w-[350px]">
            <ScrollToTop smooth color="#1DC0AD" style={{ paddingLeft: "6px" }} />
            <div className="lg:flex justify-between md:flex-none">
              <div className="md:order-last pb-10" data-aos="zoom-out" data-aos-duration="1000">
                <Image src={img1} />
              </div>
              <div className="flex justify-center">
                <div className="lg:w-[500px] md:w-[500px] sm:w-[500px] w-[350px]">
                  <div data-aos="fade-up" data-aos-duration="1000">
                    <p className="font-[400] text-[12px] text-[#1DC0AD] mb-3">OUR BELIEF</p>
                    <div className="leading-[40px]">
                      <span className="font-[300] text-[34px]">Kami percaya pada pemberdayaan teknologi untuk semua, dan sadar bahwa</span>
                      <span className="font-[900] text-[34px]"> kami dapat membuat perubahan dengan memberikan layanan teknologi yang berkualitas</span>
                    </div>
                  </div>
                  <div>
                    <div className="mt-7" data-aos="fade-up" data-aos-duration="1000">
                      <Image src={img2} />
                      <p className="font-[900] text-[18px]">Siapa yang kami bantu?</p>
                      <p className="text-[14px] font-[400] mt-2">
                        Dari usaha kecil, menengah, sampai dengan besar yang mencari teknologi dalam pekembangan dan efisiensi bisnis. Kami bertujuan untuk menjadi rekan strategis, jangka panjang yang dapat mewujudkan kebutuhan dan juga
                        menjadi lawan diskusi dari para rekan kami.
                      </p>
                    </div>
                    <div className="mt-7" data-aos="fade-up" data-aos-duration="1000">
                      <Image src={img3} />
                      <p className="font-[900] text-[18px]">Apa yang kamu percayai</p>
                      <p className="text-[14px] font-[400] mt-2">Bekerjalah dengan sepenuh hati integritas untuk memberikan hasil yang terbaik, karena kesuksesan rekan kami akan menjadi pendiri kita untuk bisa lebih berkembang juga</p>
                    </div>
                  </div>
                </div>
              </div>
            </div>
            <div className="flex justify-center">
              <div className="lg:w-[450px] w-[350px]">
                <div className="mb-7 flex justify-center" data-aos="fade-up" data-aos-duration="1000">
                  <Image src={img4} />
                </div>
                <div className="text-center">
                  <h1 className="text-[48px] -mt-6 font-[900]" data-aos="fade-up" data-aos-duration="1000">
                    Apakah kamu siap?
                  </h1>
                  <p data-aos="fade-up" data-aos-duration="1000">
                    Beritahu kami apa yang kamu mau bangun atau kesulitan apa yang kamu hadapi
                  </p>
                </div>
                <div className="mt-14 flex justify-center">
                  <button className="w-[150px] h-[55.4px] rounded-[10px] border border-[#1DC0AD] text-[#1DC0AD]" data-aos="zoom-in" data-aos-duration="1000">
                    Hubungi Kami
                  </button>
                </div>
              </div>
            </div>
          </div>
        </div>
      </Layout>
    </div>
  );
}

export default About;
