import Layout from "../components/Layout";
import Head from "next/head";
import Image from "next/image";
import img1 from "../img/about/1.gif";
import img2 from "../img/work/icn1.png";
import img3 from "../img/work/icn2.png";
import img4 from "../img/home/19.png";
import ScrollToTop from "react-scroll-to-top";

function About() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link href="https://unpkg.com/boxicons@2.1.1/css/boxicons.min.css" rel="stylesheet" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="" />
        <link href="https://fonts.googleapis.com/css2?family=Montserrat+Alternates:wght@600&family=Nunito:wght@300&display=swap" rel="stylesheet" />
        <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.8.1/font/bootstrap-icons.css"></link>
      </Head>
      <Layout>
        <ScrollToTop smooth color="#1DC0AD" style={{ paddingLeft: "6px" }} />
        <div className="lg:flex justify-between md:flex-none px-10 lg:px-36 md:px-32 sm:px-32 mt-48">
          <div className="lg:w-[600px] md:w-[650px] sm:w-[450px] mb-16">
            <div>
              <p className="font-[400] text-[12px] text-[#1DC0AD] mb-3">OUR BELIEF</p>
              <div className="leading-[40px]">
                <span className="font-[300] text-[34px]">Kami percaya pada pemberdayaan teknologi untuk semua. dan sadar bahwa</span>
                <span className="font-[900] text-[34px]"> kami dapat membuat perubahan dengan memberikan layanan teknologi yang berkualitas</span>
              </div>
            </div>
            <span className="border-b-4 border-[#1DC0AD] px-5"></span>
            <div className="">
              <div className="mt-7">
                <div className="mb-2">
                  <Image src={img2} />
                </div>
                <p className="font-[900] text-[18px]">Siapa yang kami bantu?</p>
                <p className="text-[14px] font-[400] mt-2">
                  Dari usaha kecil, menengah, sampai dengan besar yang mencari teknologi
                  <br />
                  dalam pekembangan dan efisiensi bisnis. Kami bertujuan untuk menjadi
                  <br />
                  rekan strategis, jangka panjang yang dapat mewujudkan kebutuhan dan
                  <br />
                  juga menjadi lawan diskusi dari para rekan kami.
                </p>
              </div>
              <div className="mt-7">
                <div className="mb-2">
                  <Image src={img3} />
                </div>
                <p className="font-[900] text-[18px]">Apa yang kamu percayai</p>
                <p className="text-[14px] font-[400] mt-2">
                  Bekerjalah dengan sepenuh hati integritas untuk memberikan hasil yang
                  <br />
                  terbaik, karena kesuksesan rekankami akan menjadi pendiri kita untuk
                  <br />
                  bisa lebih berkembang juga
                </p>
              </div>
            </div>
          </div>
          <div>
            <Image src={img1} />
          </div>
        </div>
        <div className="text-center">
          <div>
            <div>
              <Image src={img4} />
            </div>
            <h1 className="text-[48px] font-[900]">Apakah kamu siap?</h1>
            <p>
              Beritahu kami apa yang mau kamu bangun atau kesulitan
              <br />
              apa yang kamu hadapi
            </p>
            <button className="w-[150px] h-[55.4px] border border-[#1DC0AD] rounded-[10px] text-[18px] text-[#1DC0AD] my-20">Hubungi Kami</button>
          </div>
        </div>
      </Layout>
    </div>
  );
}

export default About;
